Description: >
  David Lee Williams / udacity project - Deploying a highly available web application
  This template deploys the Udagram web application on AWS infrastructure

Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostname: true
              
